apiVersion: v1
kind: Service
metadata:
  name: eth-load-generator-service
  namespace: load-generator
  labels:
    app: eth-load-generator
spec:
  selector:
    app: eth-load-generator
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
